default: &default
  database: postgresql://localhost/crystal_ann

test:
  database: postgresql://localhost/crystal_ann_test

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
