default: &default
  name: Crystal [ANN]
  description: Announce new project, blog post, version update or any other Crystal work
  force_ssl: false

test:
  <<: *default
  url: https://testing.com

development:
  <<: *default
  url: http://localhost:3008

staging:
  <<: *default
  url: https://crystal-ann-staging.herokuapp.com
  force_ssl: true

production:
  <<: *default
  url: https://crystal-ann.com
  force_ssl: true
